{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nijznotifier.pvc" . }}
  annotations:
  {{- with .Values.persistence.annotations  }}
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "nijznotifier.labels" . | nindent 4 }}
    {{- include "nijznotifier.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
#   persistentVolumeReclaimPolicy: Retain
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end -}}